### ISSUE TITLE
FreedomBox

### ISSUE THREAD

**Issue by peacekeeper** [OuiShare/OuiShare-Labs-Camp#10]
I could do a talk on FreedomBox, I have a few really pretty prototypes with Linked Data, remoteStorage, and other things on it.. http://projectdanube.org/wp-content/uploads/2015/04/freedombox-danube.jpg

**Comment by pierreozoux** [comment]
I though you were already confirmed :)

FreedomBox is already on the list of projects!
And I'm following project danube since quiet a while now!

Can you give a little description of the talk (for 30 mins).
And can you give me the following:
https://github.com/OuiShare/OuiShare-Labs-Camp/blob/gh-pages/_data/speakers.yml#L13-L19

With a picture.

Danke!

**Comment by kirilind** [comment]
maybe more like 10-15min talk ^___^

And yes, looking forward! Feel free to update the Freedombox description as
well if you want. >>
https://github.com/OuiShare/OuiShare-Labs-Camp/blob/gh-pages/_data/projects.yml#L49-L55

**Comment by peacekeeper** [comment]
Yes 10-15 seems enough, lots of other interesting projects out there :)
Okay will do a PR with updates to those two files.

Markus

**Comment by peacekeeper** [comment]
_Talk description:_

I will give an update of the current development status of FreedomBox and
some its functions (Tor, Linked Data, IndieWeb, remoteStorage, etc.). I'll
also present a few prototypes of a productized FreedomBox "Danube Edition".

_Speaker:_
- name: Markus Sabadello
  id: peacekeeper
  role: FreedomBox / Project Danube / XDI
  website: http://projectdanube.org/
  twitter_username: peacekeeper
  meta: Early participant of the Federated Social Web effort.
    Now contributing to FreedomBox and to a shady technology called XDI.
    Looking forward to meeting old friends and cool new people at OuiShare.

_Picture: attached_

Anything else needed?

**Comment by peacekeeper** [comment]
![mephoto](https://cloud.githubusercontent.com/assets/290941/7545948/99b6138c-f5d9-11e4-96a3-eebde01209bc.jpg)

**Comment by pierreozoux** [comment]
Here you are! http://camp.ouisharelabs.net/2015/

Thanks!
