### ISSUE TITLE
Decentralized Sharing *Community* (not Working) Group

### ISSUE THREAD

**Issue by elf-pavlik** [OuiShare/OuiShare-Labs-Camp#11]
In W3C CG IG and WG have very different role and status
- CG - https://www.w3.org/community/decsharing/
- IG - http://www.w3.org/Social/IG
- WG - http://www.w3.org/Social/WG

**Comment by kirilind** [comment]
Elf, this project has nothing to do with W3C but was initiated by Cozy and Tristan.

**Comment by pierreozoux** [comment]
We have to change it somehow because it is now part of w3c as a `community`.

**Comment by elf-pavlik** [comment]
@kirilind https://www.w3.org/community/decsharing/

I had chance few times to see confusion and tensions created by referring to Community Groups as Working Groups in context of W3C. They have very different status and work mode.
