### ISSUE TITLE
nav bar buttons don't work

### ISSUE THREAD

**Issue by maxlath** [OuiShare/OuiShare-Labs-Camp#7]
clicking on either "Home" "What?" "Who?" "Projects" "Team" or "Location" doesn't trigger scrolling to the section

**Comment by pierreozoux** [comment]
There was indeed no map :/ [fixed](https://github.com/OuiShare/OuiShare-Labs-Camp/commit/defcc0b170516c41b71e183c6339d73feb101d34)

Can you give me the javascript error from your console, I can't reproduce :/

**Comment by maxlath** [comment]
working like a charm now!
