### ISSUE TITLE
missing "location" section and instructions on how to register

### ISSUE THREAD

**Issue by maxlath** [OuiShare/OuiShare-Labs-Camp#8]

**Comment by pierreozoux** [comment]
Location is fixed as of: https://github.com/OuiShare/OuiShare-Labs-Camp/commit/defcc0b170516c41b71e183c6339d73feb101d34

**Comment by pierreozoux** [comment]
ok, not really fixed :)

**Comment by pierreozoux** [comment]
And thanks for reporting :)

**Comment by maxlath** [comment]
nice! not a very user friendly subscription process, I'm afraid few people will actually use it, but at least now there is the link that is inviting to come :)

**Comment by pierreozoux** [comment]
Hehe, @kirilind is working on an event bright also! But I like the idea to filter people somehow, it's kind of a captcha for nerds :)
